name: Create Keystore

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Create keystore
        run: |
          keytool -genkeypair \
          -v \
          -keystore upload-key.jks \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -alias cairo-upload \
          -storepass 123456 \
          -keypass 123456 \
          -dname "CN=Cairo Files, OU=Android, O=Cairo, L=Cairo, ST=Cairo, C=EG"

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: upload-key
          path: upload-key.jks
